### PR TITLE
Fix JSON logger reporting duplicate values despite configuration

### LINKED ISSUE #30: Array comparison does not work correctly
If you have an array record which is modified with a put (but keeping the first entry fixed) then caPutLog will regard that record as not having changed. Thus, if you have your configuration set to `caPutJsonLogOnChange`, it will _not_ send out a log message.

This seems to be due to the fact that the json array logic was never properly implemented, see https://github.com/epics-modules/caPutLog/blob/master/caPutLogApp/caPutLogTask.h#L36-L48; none of these union types are used anywhere in the rest of the codebase.

### PR DESCRIPTION
**Pull request by simon-ess**
This is (roughly) a cherry-pick of https://github.com/epics-modules/caPutLog/pull/5/commits/ce7bd90fe57ecb381e85731d4ddd16a2c4809beb.

Fixes #30

### CODE REVIEW

**Review by anjohnson — CHANGES_REQUESTED** [review]
I've been trying to merge this PR, but it breaks the tests.

On building the current GitHub origin/master branch at ebe7120, the program `caPutJsonLogTest` runs all its 499 tests successfully.

After hand-merging this PR's origin/cherry-pick branch locally into origin/master, `caPutJsonLogTest` hangs after printing 352 of the expected 499 results.

Checking out the tip of the cherry-pick branch at e183395 `caPutJsonLogTest` expects to run 375 tests, but it hangs after printing 331 results.

It seems that some of the test code is incompatible with duplicate values not being logged. I applied this change to the cherry-pick branch:
```patch
diff --git a/test/caPutJsonLogTest.cpp b/test/caPutJsonLogTest.cpp
index b6411d2..e135a7a 100644
--- a/test/caPutJsonLogTest.cpp
+++ b/test/caPutJsonLogTest.cpp
@@ -881,7 +881,7 @@ MAIN(caPutJsonLogTests)
     startIoc();
     CaPutJsonLogTask *logger =  CaPutJsonLogTask::getInstance();
     if (logger == NULL) testAbort("Failed to initialize logger.");
-    logger->initialize(logServerAddress.c_str(), caPutJsonLogOnChange);
+    logger->initialize(logServerAddress.c_str(), caPutJsonLogAll);
     testDiag("Test IOC ready");
     testIocReady.trigger();
 
```
The result runs to completion with all 375 tests passing.

It might be a good idea to try applying the change from this branch to earlier commits to find out if the problem appears in Matic's original or was added more recently.

It would also be good to add tests for the different settings; it's possible to switch modes at runtime so we don't have to fix all the tests, just ensure the setting in use is appropriate for each set of tests.

**Comment by simon-ess** [comment]
@anjohnson - Good catch. There definitely seems to be an issue here in comparing arrays of strings; the comparison only compares the _first_ entry in the string array; for the given test, since the first string is unchanged the "on change" check fails, even though the array has changed. As near as I can tell, despite adding the `a_string` to the types enum, it is never used: https://github.com/epics-modules/caPutLog/blob/master/caPutLogApp/caPutLogTask.h#L47

Anyhow, there are further issues in here that need to be looked at.

I'm tempted to apply your change for the time being and then create an issue to fix array put comparisons; I don't have a good sense of how much of a rabbit hole that will be. I agree that adding tests for multiple modes is a good idea, but again, rabbit hole...

**Comment by simon-ess** [comment]
@anjohnson - I have fixed the array comparison, which fixes the tests without the need for the change you suggested above.

I think it is true that we should add more varied tests, but I think it might be better to create a followup issue for that.

**Review by anjohnson — APPROVED** [review]

**Comment by anjohnson** [comment]
Yea, thanks!

**Pull request merged**
