### PR TITLE
Add counters for total puts and burst

### PR DESCRIPTION
**Pull request by henrique-silva**
The total counter is being displayed in all  information levels. My reasoning for this is that this is a basic information that would be useful to get alongside the server information on the base information level.

Implements #11

### CODE REVIEW

**Comment by anjohnson** [comment]
This new functionality looks great, thanks for doing this. There are some tests for the JSON implementation in the `test` directory, have you tried running them with your changes? Would you be able to extend them to check the new functionality as well?

The only request I have for your changes is to use the name `burst` instead of `burst_count` in the generated output logs, I like using short but meaningful names in specific cases like this.

**Comment by henrique-silva** [comment]
The current tests for the JSON logger run okay, since it doesn't check for extra fields in the log message (maybe it should?).

I'll extend the tests for the burst checking.

**Comment by ralphlange** [comment]
Sounds like an iocStats topic?!

**Comment by simon-ess** [comment]
It could be, but that adds a dependency between iocstats and caputlog that need not be there.

**Comment by ralphlange** [comment]
Not sure if that opens a can of worms...

Well, many EPICS modules have health and stats monitoring. If they don't, they should.
Should all of that be somehow plugged into iocStats? Should iocStats rather be a Base mechanism that other modules can add their things to?

**Comment by simon-ess** [comment]
That _is_ a can of worms! 😄

**Comment by anjohnson** [comment]
Doesn't iocStats already handle checking whether the sequencer is present or not at runtime? APS has been using this code to do that for years, but I see it's in our own iocStd module, not in iocStats:

```C
/* seqcaStats() is part of the sequencer, which might not be loaded */
#ifdef vxWorks
    #include <epicsFindSymbol.h>
    static void noSeq(int *pcount, int *pdiscon) {}
    /* The real seqcaStats() function is part of the sequencer, but
     * might not be loaded in this IOC.  We look it up at runtime,
     * cacheing the pointer if found, and call it if we found it.
     */
    static void seqcaStats(int *pcount, int *pdiscon) {
        static void (*seqcaStatsFunc)(int *, int *) = NULL;

        if (seqcaStatsFunc == NULL) {
            seqcaStatsFunc = epicsFindSymbol("seqcaStats");

            if (seqcaStatsFunc == NULL) {
                /* sequencer not loaded, use dummy */
                seqcaStatsFunc = noSeq;
            }
        }
        seqcaStatsFunc(pcount, pdiscon);
    }
#else
    /* everything else supports pragma weak */
    extern void seqcaStats(int *, int *);
    #pragma weak seqcaStats
#endif
```

Adding a plug-in mechanism to Base is probably better in the long run, but

**Comment by simon-ess** [comment]
@anjohnson, if there are no issues with this I would like to merge this in. The separate question about a universal mechanism to have health of IOCs aside, of course 😄

**Pull request merged**
