### PR TITLE
Expose value to string for gateway

### PR DESCRIPTION
**Pull request by FreddieAkeroyd**
Expose val_to_string() as caPutLogVALUEToString() - this is used by the EPICS gateway

### CODE REVIEW

**Comment by ralphlange** [comment]
Ping....
The CA Gateway has an open bug the fix for which needs this to be merged and released.

**Comment by bfrk** [comment]
Hi Ralph

This github project was not created by me but rather (IIRC) by Andrew, I merely converted it to git, expressly giving up maintainership in the process. I wasn't aware that I am the only developer listed here!

I have added you (Ralph) as collaborator to the github repo/project. If there is anything else I need to do to allow others to continue maintaining it, please tell me.

**Comment by ralphlange** [comment]
Oh, I wasn't aware this has been orphaned. So I could (reluctantly and constantly cursing) have a look and do what's needed.

**Comment by anjohnson** [comment]
Sorry Ralph, my bad; I'd forgotten that Ben had washed his hands of this module.

So `caPutLogVALUEToString()` is a relatively simple convenience routine for converting any value into a string, taking a dbfType to indicate the source data type. It does *not* do any logging itself or require access to any other caPutLog internal routines. I can see that this routine is convenient for the gateway to use for that purpose as it's only called when building the gateway with caPutLog support. However I have major reservations about making this routine public just for this purpose, and actually there is a bug in the gateway+caPutLog combination when building against EPICS 7.

As the gateway only communicates with IOCs through Channel Access I was expecting it to be using the Channel Access type-codes, which don't include unsigned types such as `DBR_UCHAR` or the new `DBR_INT64` codes. However the IOC's interface to the caPutLogger and all the routines in caPutLogTask.c uses the incompatible dbAccess type-codes — there is a `#include <dbFldTypes.h>` towards the top of the file.

The Gateway's `gateResources::putLog()` method calls `gddGetOurType()` which is supposed to be returning an IOC dbAccess type-code, but unfortunately it has its own copy of the `DBR_<type>` constants (which it calls `OUR_DBR_<type>` to avoid having multiple definitions). Those constants have not been updated since the 64-bit types were added to the IOC's dbfType enum, and that change altered the values of the `DBF_FLOAT` and `DBF_DOUBLE` constants. Thus building the gateway with caPutLog support will not work against EPICS 7, even with the change proposed here. The only reason the combination builds is because the DBR_INT64 macro doesn't exist, so the fact that the gateway's private `OUR_DBR_INT64`macro isn't defined anywhere isn't discovered by the compiler.

While you're fixing that, I would recommend just copying the `val_to_string()` routine into the gateway, it's only 33 lines and doing that also decouples the release versions of these two modules.

**Comment by ralphlange** [comment]
Thanks for the explanations, Andrew!
Your proposal does indeed sound easier - I will proceed along those lines. (And keep my fingers off caPutLog - thanks for saving me.)

**Comment by anjohnson** [comment]
@FreddieAkeroyd thanks for your time on this, but @ralphlange will be coming up with a better solution.

**Pull request closed without merging**
